name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: >
          xcodebuild
          -scheme Maclippy
          -destination 'platform=macOS'
          -configuration Release
          build
          CODE_SIGNING_ALLOWED=NO
